### ISSUE TITLE
Cavy works in react-native 0.42.3?

### ISSUE THREAD

**Issue by jtlimo** [pixielabs/cavy#23]
I'm trying to test my simple app with cavy, but cavy doesn't work well.

Here is my configuration:

```
react-native: 0.42.3
react-native-cli: 2.0.1
```

When I install cavy, shows up a warning: 

`npm WARN cavy@0.3.1 requires a peer of react-native@0.40.x but none was installed.`

When run at android, shows an error:

`undefined is not a function (evaluating 'this.props.generateTestHook('PaginaInicial.PontoButton')')`

I had imported hook from cavy, and exported: `export default hook(PaginaInicial);`

I'm really new in react-native and cavy, so sorry if my issue it's not about cavy; 

Tks;

**Comment by jalada** [comment]
Hi @jtlimo, thanks for trying out Cavy!

I don't think the version mismatch is the issue, though we need to check Cavy's compatibility with 0.42.3. You can check yourself by installing an older compatible version of React Native and seeing if the same issue presents itself.

Is `PaginaInicial` a stateless component? Cavy doesn't work properly with stateless components: https://github.com/pixielabs/cavy/issues/18

**Comment by jtlimo** [comment]
Hi @jalada , tks for answering;
I update the react-native to 
```
react-native-cli: 2.0.1
react-native: 0.43.3

```

And I get the same error.

`PaginaInicial` is a class component;

```
class PaginaInicial extends Component {

}

```
I export PaginaInicial in the end of file;

`module.exports = PaginaInicial;`

**Comment by jalada** [comment]
@jtlimo you made your react-native version even newer, not older... 😞

**Comment by jtlimo** [comment]
@jalada I put my react-native version newer, because the employee tests works in the newer version of  react-native.

**Comment by jalada** [comment]
@jtlimo did you ever manage to get this working?

**Comment by rodolfobarretoweb** [comment]
Oi Jéssica, você conseguiu fazer isso funcionar ? Se sim, você usa redux no projeto ?

**Comment by jtlimo** [comment]
@rodolfobarretoweb Eu não consegui fazer funcionar, acabei desistindo, mas pretendo a mexer novamente nele. Não usa redux no projeto (mas era projeto pessoal e acabei deixando de lado =/ )

**Comment by raj040492** [comment]
Hi, I am using 
"react": "15.4.1",   "react-native": "0.40.0", "cavy" : "0.4.0"

Suffering from the above error; 
undefined is not a function (evaluating 'this.props.generateTestHook.....

any suggestions?

**Comment by jalada** [comment]
@raj040492 Have you definitely `hook()`d your component as per [this bit of the README](https://github.com/pixielabs/cavy#hook-up-components-for-testing)?

**Comment by jalada** [comment]
Closing this issue but feel free to continue discussion
